global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'app-python'
    static_configs:
      - targets: ['app-python:8000']
    metrics_path: '/metricas'

  - job_name: 'app-go'
    static_configs:
      - targets: ['app-go:8001']
    metrics_path: '/metricas'

  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
